package wsdl.magazzino_principale.acme.org;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-02-22T13:44:35.019+01:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "org.acme.magazzino-principale.wsdl", name = "MySelf")
@XmlSeeAlso({xsd.magazzino_principale.acme.org.ObjectFactory.class})
public interface MySelf {

    @WebMethod(action = "eliminaPrenotazioneMagazzino")
    @RequestWrapper(localName = "eliminaPrenotazioneMagazzino", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.EliminaPrenotazioneMagazzino")
    @ResponseWrapper(localName = "eseguiOrdineMagazzinoResponse", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.EseguiOrdineMagazzinoResponse")
    public void eliminaPrenotazioneMagazzino(
        @WebParam(name = "idMagazzino", targetNamespace = "")
        int idMagazzino,
        @WebParam(name = "idOrdine", targetNamespace = "")
        int idOrdine
    );

    @WebMethod(action = "prenotaPezziMagazzini")
    @RequestWrapper(localName = "prenotaPezziMagazzini", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.PrenotaPezziMagazzini")
    @ResponseWrapper(localName = "prenotaPezziMagazzinoResponse", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.PrenotaPezziMagazzinoResponse")
    @WebResult(name = "pezzi", targetNamespace = "")
    public java.util.List<xsd.magazzino_principale.acme.org.Pezzo> prenotaPezziMagazzini(
        @WebParam(name = "pezziMagazzino", targetNamespace = "")
        java.util.List<xsd.magazzino_principale.acme.org.PezziMagazzino> pezziMagazzino,
        @WebParam(name = "utente", targetNamespace = "")
        xsd.magazzino_principale.acme.org.Utente utente,
        @WebParam(name = "idOrdine", targetNamespace = "")
        int idOrdine
    );

    @WebMethod(action = "verificaDisponibilitaMagazzini")
    @RequestWrapper(localName = "verificaDisponibilitaMagazzini", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.VerificaDisponibilitaMagazzini")
    @ResponseWrapper(localName = "verificaDisponibilitaMagazziniResponse", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.VerificaDisponibilitaMagazziniResponse")
    public void verificaDisponibilitaMagazzini(
        @WebParam(name = "pezzi", targetNamespace = "")
        java.util.List<xsd.magazzino_principale.acme.org.Pezzo> pezzi,
        @WebParam(name = "utente", targetNamespace = "")
        xsd.magazzino_principale.acme.org.Utente utente,
        @WebParam(mode = WebParam.Mode.OUT, name = "disponibilitaPezzi", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<xsd.magazzino_principale.acme.org.DisponibilitaPezzi>> disponibilitaPezzi,
        @WebParam(mode = WebParam.Mode.OUT, name = "pezziMancanti", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<xsd.magazzino_principale.acme.org.Pezzo>> pezziMancanti
    );

    @WebMethod(action = "eliminaPrenotazioneFornitore")
    @RequestWrapper(localName = "eliminaPrenotazioneFornitore", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.EliminaPrenotazioneFornitore")
    @ResponseWrapper(localName = "eseguiOrdineMagazzinoResponse", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.EseguiOrdineMagazzinoResponse")
    public void eliminaPrenotazioneFornitore(
        @WebParam(name = "idMagazzino", targetNamespace = "")
        int idMagazzino,
        @WebParam(name = "idOrdine", targetNamespace = "")
        int idOrdine
    );

    @WebMethod(action = "assemblaCiclo")
    @Oneway
    @RequestWrapper(localName = "assemblaCiclo", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.AssemblaCiclo")
    public void assemblaCiclo(
        @WebParam(name = "idOrdine", targetNamespace = "")
        int idOrdine
    );

    @WebMethod(action = "verificaDisponibilitaMagazzino")
    @RequestWrapper(localName = "verificaDisponibilitaMagazzino", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.VerificaDisponibilitaMagazzino")
    @ResponseWrapper(localName = "verificaDisponibilitaMagazzinoResponse", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.VerificaDisponibilitaMagazzinoResponse")
    @WebResult(name = "pezziDisponibili", targetNamespace = "")
    public java.util.List<xsd.magazzino_principale.acme.org.Pezzo> verificaDisponibilitaMagazzino(
        @WebParam(name = "idMagazzino", targetNamespace = "")
        int idMagazzino,
        @WebParam(name = "pezzi", targetNamespace = "")
        java.util.List<xsd.magazzino_principale.acme.org.Pezzo> pezzi
    );

    @WebMethod(action = "prenotaPezziMagazzino")
    @RequestWrapper(localName = "prenotaPezziMagazzino", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.PrenotaPezziMagazzino")
    @ResponseWrapper(localName = "prenotaPezziMagazzinoResponse", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.PrenotaPezziMagazzinoResponse")
    public void prenotaPezziMagazzino(
        @WebParam(name = "idMagazzino", targetNamespace = "")
        int idMagazzino,
        @WebParam(mode = WebParam.Mode.INOUT, name = "pezzi", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<xsd.magazzino_principale.acme.org.Pezzo>> pezzi,
        @WebParam(name = "utente", targetNamespace = "")
        xsd.magazzino_principale.acme.org.Utente utente,
        @WebParam(name = "idOrdine", targetNamespace = "")
        int idOrdine
    );

    @WebMethod(action = "verificaDisponibilitaFornitore")
    @RequestWrapper(localName = "verificaDisponibilitaFornitore", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.VerificaDisponibilitaFornitore")
    @ResponseWrapper(localName = "verificaDisponibilitaFornitoreResponse", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.VerificaDisponibilitaFornitoreResponse")
    @WebResult(name = "pezziDisponibili", targetNamespace = "")
    public java.util.List<xsd.magazzino_principale.acme.org.PezzoConPrezzo> verificaDisponibilitaFornitore(
        @WebParam(name = "pezzi", targetNamespace = "")
        java.util.List<xsd.magazzino_principale.acme.org.Pezzo> pezzi,
        @WebParam(name = "idFornitore", targetNamespace = "")
        int idFornitore,
        @WebParam(name = "utente", targetNamespace = "")
        xsd.magazzino_principale.acme.org.Utente utente
    );

    @WebMethod(action = "prenotaPezziFornitore")
    @RequestWrapper(localName = "prenotaPezziFornitore", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.PrenotaPezziFornitore")
    @ResponseWrapper(localName = "prenotaPezziMagazzinoResponse", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.PrenotaPezziMagazzinoResponse")
    public void prenotaPezziFornitore(
        @WebParam(name = "idMagazzino", targetNamespace = "")
        int idMagazzino,
        @WebParam(mode = WebParam.Mode.INOUT, name = "pezzi", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<xsd.magazzino_principale.acme.org.Pezzo>> pezzi,
        @WebParam(name = "utente", targetNamespace = "")
        xsd.magazzino_principale.acme.org.Utente utente,
        @WebParam(name = "idOrdine", targetNamespace = "")
        int idOrdine
    );

    @WebMethod(action = "eseguiOrdineFornitore")
    @RequestWrapper(localName = "eseguiOrdineFornitore", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.EseguiOrdineFornitore")
    @ResponseWrapper(localName = "eseguiOrdineMagazzinoResponse", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.EseguiOrdineMagazzinoResponse")
    public void eseguiOrdineFornitore(
        @WebParam(name = "idMagazzino", targetNamespace = "")
        int idMagazzino,
        @WebParam(name = "idOrdine", targetNamespace = "")
        int idOrdine
    );

    @WebMethod(action = "eseguiOrdineMagazzino")
    @RequestWrapper(localName = "eseguiOrdineMagazzino", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.EseguiOrdineMagazzino")
    @ResponseWrapper(localName = "eseguiOrdineMagazzinoResponse", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.EseguiOrdineMagazzinoResponse")
    public void eseguiOrdineMagazzino(
        @WebParam(name = "idMagazzino", targetNamespace = "")
        int idMagazzino,
        @WebParam(name = "idOrdine", targetNamespace = "")
        int idOrdine
    );

    @WebMethod(action = "creaIstanzaOrdine")
    @RequestWrapper(localName = "creaIstanzaOrdine", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.CreaIstanzaOrdine")
    @ResponseWrapper(localName = "eseguiOrdineMagazzinoResponse", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.EseguiOrdineMagazzinoResponse")
    public void creaIstanzaOrdine(
        @WebParam(name = "pezziMagazzino", targetNamespace = "")
        java.util.List<xsd.magazzino_principale.acme.org.PezziMagazzino> pezziMagazzino,
        @WebParam(name = "utente", targetNamespace = "")
        xsd.magazzino_principale.acme.org.Utente utente,
        @WebParam(name = "idOrdine", targetNamespace = "")
        int idOrdine
    );

    @WebMethod(action = "eliminaPrenotazioneMagazzini")
    @RequestWrapper(localName = "eliminaPrenotazioneMagazzini", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.EliminaPrenotazioneMagazzini")
    @ResponseWrapper(localName = "eseguiOrdineMagazzinoResponse", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.EseguiOrdineMagazzinoResponse")
    public void eliminaPrenotazioneMagazzini(
        @WebParam(name = "idOrdine", targetNamespace = "")
        int idOrdine
    );

    @WebMethod(action = "eseguiOrdineMagazzini")
    @RequestWrapper(localName = "eseguiOrdineMagazzini", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.EseguiOrdineMagazzini")
    @ResponseWrapper(localName = "eseguiOrdineMagazzinoResponse", targetNamespace = "org.acme.magazzino-principale.xsd", className = "xsd.magazzino_principale.acme.org.EseguiOrdineMagazzinoResponse")
    public void eseguiOrdineMagazzini(
        @WebParam(name = "idOrdine", targetNamespace = "")
        int idOrdine
    );
}
