package wsdl.magazzino_principale.acme.org;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-02-19T16:50:16.483+01:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "MySelfService", 
                  wsdlLocation = "classpath:magazzinoPrincipale.wsdl",
                  targetNamespace = "org.acme.magazzino-principale.wsdl") 
public class MySelfService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("org.acme.magazzino-principale.wsdl", "MySelfService");
    public final static QName MySelfServicePort = new QName("org.acme.magazzino-principale.wsdl", "MySelfServicePort");
    static {
        URL url = MySelfService.class.getClassLoader().getResource("magazzinoPrincipale.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(MySelfService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:magazzinoPrincipale.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public MySelfService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MySelfService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MySelfService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MySelfService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MySelfService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MySelfService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns MySelf
     */
    @WebEndpoint(name = "MySelfServicePort")
    public MySelf getMySelfServicePort() {
        return super.getPort(MySelfServicePort, MySelf.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MySelf
     */
    @WebEndpoint(name = "MySelfServicePort")
    public MySelf getMySelfServicePort(WebServiceFeature... features) {
        return super.getPort(MySelfServicePort, MySelf.class, features);
    }

}
